### ISSUE TITLE
Export to PDF Fatal Error Message

### ISSUE THREAD

**Issue by Josh1711** [lanternbox/exploreCRS#12]
Hello Lantern,

Today I discovered an issue that I haven't come across before related to a fatal error due to lack of memory. I went to a candidates profile, "Hanna Bakour" number 4151, and clicked on the "Export to PDF" button to do download the PDF, something I have done numerous times without any problem, and today it ended up with the following message:

![image](https://cloud.githubusercontent.com/assets/23716044/20703240/f32893ac-b655-11e6-870b-f53dde3e6260.png)

This hasn't happened before to me on any other profile and about 10 minutes before this error occurred I was exporting to PDF with no problems. 
Thanks.

Josh

**Comment by lantern-andrew** [comment]
Hi Josh,

Thanks for the error message and screenshot.

We checked and found that Hanna's portrait image was 10MB. It seems this was causing the "out of memory" error you reported. We downloaded the image, resaved it at a smaller file size, and reuploaded. Now the pdf export is working for us.

Please try again, and let us know if you have any more issues.

Thanks,
Andrew

**Comment by Josh1711** [comment]
Hey Andrew,

Thank you for the rapid response, much appreciated. It does work and now that I understand the issue I will resolve myself next time thank you kindly for the help.

Best,

Josh
