### ISSUE TITLE
emails from robin@explorecrs.com not delivering internally

### ISSUE THREAD

**Issue by RobinWatts1** [lanternbox/exploreCRS#14]
I am finding that emails from my 'robin@explorecrs.com' are not delivering to Dipont staff using firstname.surname@dipont-edu.com.  It is possible that this may be happening with external company email addresses too but I can't confirm.  Is it ok to ask the physical location of the server?  As I wondered if this might be causing the email to be filtered or blocked.

Kind regards,

Robin

**Comment by lantern-jingjing** [comment]
Hi Robin,
Thanks for your report.
To help us figure it out , would you please send us the screen shots for any error message when you try to send the email to firstname.surname@dipont-edu.com? If you did not get any error message, just click "send" button and nothing happen, please also send us the original screen shot for that.
Many thanks,
Jingjing

**Comment by RobinWatts1** [comment]
[Emails from robin@explorecrs.com not getting through.docx](https://github.com/lanternbox/exploreCRS/files/623824/Emails.from.robin.explorecrs.com.not.getting.through.docx)

Hi Jingjing and Andrew, the screenshots of mine and my colleagues computer are attached, I don't get an error message.

Thanks for your support,

Kind regards,

Robin

**Comment by RobinWatts1** [comment]
Hi Jingjing and Andrew, the screenshots of mine and my colleagues computer are attached, I don't get an error message.

 

Thanks for your support,

 

Kind regards,

 

Robin

 

explore_logo-400x400-tw 

Robin Watts / Recruitment Consultant  
 <mailto:duy@explorecrs.com> robin@explorecrs.com

# 86 (0)21 6248 2686

Skype: robinstuartwatts 

 

Explore CRS 

Suite 505-507, 65 West Yan'an Road 

Shanghai, 200040, China 

 <http://www.explorecrs.com/> explorecrs.com

 

 <https://www.linkedin.com/company/2376224?trk=prof-0-ovw-curr_pos> linkedin   <https://twitter.com/exploreCRS> twitter.jpg   <https://www.facebook.com/learningleaders.xyz/?hc_ref=SEARCH&fref=nf> face.png  


 

Save the Date: explore CRS International Schools Recruitment Fairs

 

Shanghai: January 13 - 15, 2017


Abu Dhabi: January 19 - 21, 2017

 

	

 


Please visit  <http://www.explorecrs.com/> www.explorecrs.com  for further information or to register.

 

Feel free to forward this information to any friends or colleagues looking for positions at international schools in Asia and the Middle East.

**Comment by lantern-jingjing** [comment]
Hi Robin,
I did not find any screen shots here, would you please try to attach them again?
Many thanks,
Jingjing

**Comment by RobinWatts1** [comment]
Hi Jing Jing,

 

Sorry I might have forgotten to attach it, should be attached now.

 

Kind regards,

 

Robin

 

explore_logo-400x400-tw 

Robin Watts / Recruitment Consultant  
 <mailto:duy@explorecrs.com> robin@explorecrs.com

# 86 (0)21 6248 2686

Skype: robinstuartwatts 

 

Explore CRS 

Suite 505-507, 65 West Yan'an Road 

Shanghai, 200040, China 

 <http://www.explorecrs.com/> explorecrs.com

 

 <https://www.linkedin.com/company/2376224?trk=prof-0-ovw-curr_pos> linkedin   <https://twitter.com/exploreCRS> twitter.jpg   <https://www.facebook.com/learningleaders.xyz/?hc_ref=SEARCH&fref=nf> face.png  


 

Save the Date: explore CRS International Schools Recruitment Fairs

 

Shanghai: January 13 - 15, 2017


Abu Dhabi: January 19 - 21, 2017

 

	

 


Please visit  <http://www.explorecrs.com/> www.explorecrs.com  for further information or to register.

 

Feel free to forward this information to any friends or colleagues looking for positions at international schools in Asia and the Middle East.

**Comment by lantern-jingjing** [comment]
Hi Robin,
I still did not find the screen shots. Would you please try to go to the GitHub website to reply and attach the screenshot or send it to j.chen@lanterndesign.com directly?

**Comment by lantern-jingjing** [comment]
Hi Robin,
Thanks for sending us he screen shot, would you let me know if the address you sent to is bryanna. jin@dipont-edu.com?
Many thanks,
Jingjing

**Comment by RobinWatts1** [comment]
Hi Jing Jing,

 

Yes, the address was bryanna.jin@dipont-edu.com

 

Kind regards,

 

Robin

 

explore_logo-400x400-tw 

Robin Watts / Recruitment Consultant  
 <mailto:duy@explorecrs.com> robin@explorecrs.com

# 86 (0)21 6248 2686

Skype: robinstuartwatts 

 

Explore CRS 

Suite 505-507, 65 West Yan'an Road 

Shanghai, 200040, China 

 <http://www.explorecrs.com/> explorecrs.com

 

 <https://www.linkedin.com/company/2376224?trk=prof-0-ovw-curr_pos> linkedin   <https://twitter.com/exploreCRS> twitter.jpg   <https://www.facebook.com/learningleaders.xyz/?hc_ref=SEARCH&fref=nf> face.png  


 

Save the Date: explore CRS International Schools Recruitment Fairs

 

Shanghai: January 13 - 15, 2017


Abu Dhabi: January 19 - 21, 2017

 

	

 


Please visit  <http://www.explorecrs.com/> www.explorecrs.com  for further information or to register.

 

Feel free to forward this information to any friends or colleagues looking for positions at international schools in Asia and the Middle East.

**Comment by lantern-jingjing** [comment]
Hi Robin,

Thanks for your confirmation.

We checked the mail server logs, and we found the following relevant entry there:
2016-12-01 14:35:00.822618500 delivery 637302: success: 
![delivery success](https://cloud.githubusercontent.com/assets/23452505/20788715/d8b29480-b7ec-11e6-8a23-317b98c83ab4.jpg)
It shows that the message has been correctly sent and accepted for delivery by the remote mail server. There was a slight delay with the initial delivery, as the message was temporarily deferred. However, it was accepted for delivery shortly afterwards.

Let us know if we can assist you with anything else.

Best regards,
Jingjing

**Comment by RobinWatts1** [comment]
Hi Jing Jing,

 

I have just asked my colleague and attached is the screen shot from her
mailbox now with the email still undelivered from my robin@explorecrs.com.
Thanks for looking into it.

 

Kind regards,

 

Robin

 

explore_logo-400x400-tw 

Robin Watts / Recruitment Consultant  
 <mailto:duy@explorecrs.com> robin@explorecrs.com

# 86 (0)21 6248 2686

Skype: robinstuartwatts 

 

Explore CRS 

Suite 505-507, 65 West Yan'an Road 

Shanghai, 200040, China 

 <http://www.explorecrs.com/> explorecrs.com

 

 <https://www.linkedin.com/company/2376224?trk=prof-0-ovw-curr_pos> linkedin
<https://twitter.com/exploreCRS> twitter.jpg
<https://www.facebook.com/learningleaders.xyz/?hc_ref=SEARCH&fref=nf>
face.png  


 

Save the Date: explore CRS International Schools Recruitment Fairs

 

Shanghai: January 13 - 15, 2017


Abu Dhabi: January 19 - 21, 2017

 

	

 


Please visit  <http://www.explorecrs.com/> www.explorecrs.com  for further
information or to register.

 

Feel free to forward this information to any friends or colleagues looking
for positions at international schools in Asia and the Middle East.

 

 

From: Bryanna Jin [mailto:bryanna.jin@dipont-edu.com] 
Sent: 2016年12月1日 17:59
To: 'Robin Watts'
Subject: 答复: Test

 

Hi Robin,

 

Please kindly check the doc attached.

 

Kind regards,

Bryanna

 

 

金鲁丹 Miss Bryanna Jin

Expat Staff HR Specialist

Dipont Education Management Group

Tel: (021) 62483646 ext 8020

Add: Suite 505-507, 5th floor, 228 Huashan Rd, the Equatorial Hotel Office
Building, Jing'an District, Shanghai. 200040.

Web: www.dipont.com

           www.dipont-edu.org

 

发件人: Robin Watts [mailto:robin@crs-edu.com] 
发送时间: 2016年12月1日 14:44
收件人: 'Bryanna Jin'
主题: RE: Test

 

Thanks Bryanna,

 

That help is really appreciated

 

From: Bryanna Jin [mailto:bryanna.jin@dipont-edu.com] 
Sent: 2016年12月1日 14:36
To: 'Robin Watts'
Subject: 答复: Test

 

Hi Robin,

 

Please kindly find the doc attached.

 

Kind regards,

Bryanna

 

 

金鲁丹 Miss Bryanna Jin

Expat Staff HR Specialist

Dipont Education Management Group

Tel: (021) 62483646 ext 8020

Add: Suite 505-507, 5th floor, 228 Huashan Rd, the Equatorial Hotel Office
Building, Jing'an District, Shanghai. 200040.

Web: www.dipont.com

           www.dipont-edu.org

 

发件人: Robin Watts [mailto:robin@crs-edu.com] 
发送时间: 2016年12月1日 14:33
收件人: 'Bryanna Jin'
主题: Test

 

Hi Bryanna,

 

Could you just see if you received a previous email from me from my other
account and let me know?

 

Kind regards,

 

Robin

 

 


 


 <http://www.crs-edu.com/> cid:image001.png@01D0C88A.434E4770

Robin Watts / Consultant 

Recruitment Coordinator Dipont Education
 <mailto:angela@crs-edu.com> robin@crs-edu.com

 

CRS Education 
+86 021 6248 2686 
Suite 505-507, 65 West Yan'an Road 

Shanghai, 200040, China 

 

Save the Date: CRS International Schools Recruitment Fairs

Shanghai: January 13 - 15, 2017


Abu Dhabi: January 19 - 21, 2017

**Comment by lantern-jingjing** [comment]
Hi Robin,

Thanks for your more info.

Our server is working well and it shows that your email has been sent successfully. 

You could ask Bryanna to check her both inbox and junk box to see if the email is there.

Many thanks,
Jingjing

**Comment by RobinWatts1** [comment]
Hi Jing Jing,

 

Please see attached Bryanna’s screenshot of her junk mail.  She has reported no noticeable issues with her inbox and my email is not landing in the junk.

 

Thanks for your support,

 

Robin

 

explore_logo-400x400-tw 

Robin Watts / Recruitment Consultant  
 <mailto:duy@explorecrs.com> robin@explorecrs.com

# 86 (0)21 6248 2686

Skype: robinstuartwatts 

 

Explore CRS 

Suite 505-507, 65 West Yan'an Road 

Shanghai, 200040, China 

 <http://www.explorecrs.com/> explorecrs.com

 

 <https://www.linkedin.com/company/2376224?trk=prof-0-ovw-curr_pos> linkedin   <https://twitter.com/exploreCRS> twitter.jpg   <https://www.facebook.com/learningleaders.xyz/?hc_ref=SEARCH&fref=nf> face.png  


 

Save the Date: explore CRS International Schools Recruitment Fairs

 

Shanghai: January 13 - 15, 2017


Abu Dhabi: January 19 - 21, 2017

 

	

 


Please visit  <http://www.explorecrs.com/> www.explorecrs.com  for further information or to register.

 

Feel free to forward this information to any friends or colleagues looking for positions at international schools in Asia and the Middle East.

**Comment by lantern-jingjing** [comment]
Hi Robin,

Thanks for your reply.

We double checked our server, and they confirmed with us that the email was sent successfully. We have no control for dipont-edu.com email, so we could not know what happened in their side.

Do you have any other cases like that? If you do, please send the info to us and we can track it case by case.

Many thanks,
Jingjing
