### ISSUE TITLE
Email Bounce Back

### ISSUE THREAD

**Issue by Josh1711** [lanternbox/exploreCRS#17]
Hi, 

I received an email from a referee for one of my candidates who is trying to send me a reference form that is completed but our email server keeps bouncing him back and not allowing it to go through. Any ideas why this would be happening and what should I do to get the email and reference form? Thanks.

![bounce back](https://cloud.githubusercontent.com/assets/23716044/21000323/1dde8c4a-bd55-11e6-8695-984c44cb15d5.JPG)

**Comment by lantern-jingjing** [comment]
Hi Josh,
Can you please let us know the sender email address of that message? 
Many thanks,
Jingjing

**Comment by Josh1711** [comment]
Hi JingJing,

The email address he used was the one below
patrick_farrlley@smicschool.com

He was able to send me an email from his personal email account.

Thanks,

Josh

**Comment by lantern-jingjing** [comment]
Hi Josh,

Thanks for your info.

Just to let you know that everything is working well for our server and your email account. 

The message was blocked by one of the anti-spam systems on our servers. It is called Spamdyke. This tool performs DNS checks on the addresses of all machines that try to relay email to our servers, and if their IP address does not resolve back to a hostname, the message is rejected. You can find more information about Spamdyke at http://suresupport.com/faq/10/380

There are two options in such cases:
1. You can contact the sender and ask them to discuss the rDNS issue with their system administrator/ISP.
or
2. We can disable the Spamdyke filtering for explorecrs mail server. This will resolve this problem, but will also result in more spam messages received in all the accounts' mailboxes. **Please let us know if you want us to disable the Spamdyke filtering.**

Many thanks,
Jingjing

**Comment by lantern-andrew** [comment]
Hi Josh, we're closing this ticket for now. If you do want the anti-spam filter disabled, or have any more questions about this particular issue, you can let us know any time.
