### ISSUE TITLE
Subject List for Primary on the Profiles

### ISSUE THREAD

**Issue by Josh1711** [lanternbox/exploreCRS#18]
Hi, 

We need to add a SEN (Special Educational Needs) choice under experience for the primary school experience section. It is something we missed off and if you could do that it would be great thanks.

![image](https://cloud.githubusercontent.com/assets/23716044/21040566/bd7becea-be20-11e6-8510-7c9f5ff7dc47.png)

**Comment by lantern-jingjing** [comment]
Hi Josh,

Ok, we will add it to our next launch.

Best regards,
Jingjing

**Comment by lantern-andrew** [comment]
Hi Josh, the new subject you requested has been posted. You can find it in the candidate profile, and it will also appear in the new candidate search.
