### ISSUE TITLE
Weird Profile

### ISSUE THREAD

**Issue by Josh1711** [lanternbox/exploreCRS#19]
Hi Andrew,

I have a profile which seems to have no other buttons other than the save profile button. It also doesn't the link to upload the completed profile pack. It seems that this profile is a new profile, but it doesnt have any of the new functions.

![image](https://cloud.githubusercontent.com/assets/23716044/21132476/388dcd96-c14f-11e6-8dc1-b23ab4bb2463.png)
![image](https://cloud.githubusercontent.com/assets/23716044/21132483/3fb863e2-c14f-11e6-94a1-2c4cbea862bc.png)

**Comment by lantern-andrew** [comment]
Hi Josh, 

Sorry for my delay getting back to you about this, and thanks for your patience.

The appearance of the extra buttons depends entirely on whether you are logged in as an admin through the CMS. If you see the buttons are missing, it means you're in the candidate's profile but not logged in as an admin.

In any case, I've double checked this candidate's profile just now (through the CMS) and all buttons are there. If you have any more questions, you're welcome to let me know.

Thanks,
Andrew

**Comment by Josh1711** [comment]
Hi Andrew,

Thanks for the help, It is probably right although I was thought I was logged in. Apparently not though, thanks.
