### ISSUE TITLE
Missing Date of Birth

### ISSUE THREAD

**Issue by Josh1711** [lanternbox/exploreCRS#20]
Hi Andrew,

This is an issue that others have had also. It seems that on occasion the profiles don't save the date of birth information. It doesn't seem to do that with every profile but on and off we seem to get profiles that have the DOB in missing and we are not sure why. Having asked this to some candidates when we interview them, they often say they had completed the DOB section but it seems to not save. Could you let me know what might be causing this? Thanks. Below are three examples. There are others but we often fix it by asking them their DOB. 

![image](https://cloud.githubusercontent.com/assets/23716044/21298412/caa6b3e8-c5cb-11e6-89c9-3c9707066865.png)
![image](https://cloud.githubusercontent.com/assets/23716044/21298427/f11c125c-c5cb-11e6-8e06-3b1ee5f937d0.png)
![image](https://cloud.githubusercontent.com/assets/23716044/21298479/bf46ab88-c5cc-11e6-9af7-a527153963ef.png)

**Comment by lantern-andrew** [comment]
Hi Josh, thanks for reporting this to us - in fact Angela had also mentioned it before in a meeting.

We checked and found our calendar popup was not working in old versions of Internet Explorer. (The date could still be entered manually.)

We installed a new calendar popup that works in old IE versions. I think this should address the issue, so I'm closing the ticket. If you do run into it again, please let us know.
