### ISSUE TITLE
Attachment Function in School Email to Candidates

### ISSUE THREAD

**Issue by AngelaCRS** [lanternbox/exploreCRS#21]
Hi,

Would it be possible to add an attachment function for the school email to candidates? Right now it's not possible to send any documents in the initial email schools send out and a principal has asked if that could be added.

Thanks!

Best regards,
Angela

**Comment by lantern-andrew** [comment]
Hi Angela,

We will review this request with Naomi at our next meeting (Thursday AM).

Thanks,
Andrew

**Comment by lantern-andrew** [comment]
Feature added and uploaded to live site on Jan 10 - closing ticket
