### ISSUE TITLE
Odd tag for candidate Danilo Alcontin

### ISSUE THREAD

**Issue by AngelaCRS** [lanternbox/exploreCRS#22]
Hi,

I was searching through the candidate database and noticed this odd tag for Candidate Danilo Alcontin which I don't think belongs in his profile. It shows early years generalist on the top row and he has not selected early years at all. Please see screenshot to see what I mean.

![image](https://cloud.githubusercontent.com/assets/23715436/21495019/3a59bff2-cc50-11e6-972f-d9af66e26426.png)

**Comment by AngelaCRS** [comment]
Hi

Candidate Hector Ospina also has a tag that shouldn't be appearing which is "Other Subject" on the second row next to "Primary/Elementary." If you look at his profile he doesn't have other selected underneath the subjects section for primary. Please see screen shot below.

![image](https://cloud.githubusercontent.com/assets/23715436/21495485/b14b4228-cc52-11e6-9401-51b000eb0013.png)

**Comment by AngelaCRS** [comment]
Here is another example from another candidate Waddah Al-Alem with an odd tag. Please see screenshot below.

![image](https://cloud.githubusercontent.com/assets/23715436/21495758/7f3e6c4a-cc54-11e6-9237-83fefa4980e9.png)

**Comment by lantern-andrew** [comment]
Hi Angela,

Thanks for the details and screenshots.

Danilo Alcontin
It seems this candidate (or a consultant) had done the following:
1) for "Age Range of Students", selected "Early Years"
2) for "Early Years", selected "Early Years Generalist", then
3) back at "Age Range of Students", deleted "Early Years"

The result was that the "Early Years Generalist" tag was still selected, even though its parent "Early Years" age group wasn't. We deleted it just now and everything looks ok.

![screen shot 2016-12-27 at 4 36 20 pm](https://cloud.githubusercontent.com/assets/23451422/21495876/3a0dcda4-cc55-11e6-880c-dd3dd4ce9701.png)




Hector Ospina
You reported the candidate had a strange tag "Other Subject: ". In fact the candidate's profile did show that in the "other subject" field, a blank character had been entered, which the search was then correctly reporting. We deleted that blank character and the tag is now gone.

![screen shot 2016-12-27 at 4 40 13 pm](https://cloud.githubusercontent.com/assets/23451422/21495878/3d219b7e-cc55-11e6-8545-d3b83a48dced.png)

**Comment by lantern-andrew** [comment]
Hi Angela, I went ahead and addressed the other related cases you just reported, so will go ahead and close the ticket now.

If there is some reason any consultants are entering blank spaces in the "other" fields, please let me know.
