### ISSUE TITLE
Personal Details Changes on Candidate Profiles

### ISSUE THREAD

**Issue by Josh1711** [lanternbox/exploreCRS#24]
We have checked today and it seems that under the personal details section, the number of dependents and the drop down boxes have changed.

Previously we could select the number of dependents, the sex and the age of each dependent. Now however, we can still select the number of dependents but can only choose the sex and age for a maximum of 2. 

E.g. if a candidate has one dependent it will look like this:

![image](https://cloud.githubusercontent.com/assets/23716044/21831869/1b08a85a-d7e2-11e6-9a33-069d924f25aa.png)

or if a candidate has 2 children you can only choose the age and sex of one of the children.

![image](https://cloud.githubusercontent.com/assets/23716044/21831880/3632c73c-d7e2-11e6-8904-9514b5c83ff7.png)

**Comment by lantern-andrew** [comment]
Hi Josh, thanks for pointing that out. Just a bug - it's fixed now.
