### ISSUE TITLE
Job Search Locations

### ISSUE THREAD

**Issue by Josh1711** [lanternbox/exploreCRS#25]
Hi, the locations for the job search should be done by region, not by country. Please could you change asap. Thanks.

![git hubn](https://cloud.githubusercontent.com/assets/23716044/21835801/c57088a4-d7fa-11e6-8c8d-c2d18819517f.jpg)

**Comment by lantern-andrew** [comment]
Hi Josh, indeed it should be regions. We've just updated it. Thanks for pointing it out.
