### ISSUE TITLE
Candidate Search

### ISSUE THREAD

**Issue by Josh1711** [lanternbox/exploreCRS#27]
It appears that on the candidate search database schools can only see 10 candidates per search and they cannot click next or more candidates. The more candidates function doesn't do anything. This is very important as the schools need access to all potential candidates under a certain search term.

**Comment by lantern-andrew** [comment]
Hi Josh, the candidate search is working well for us here. Have you tested yourself or is this according to a school's report? Would you be able to provide their screenshot? Thanks, Andrew
