### ISSUE TITLE
Pack upload failure

### ISSUE THREAD

**Issue by RobinWatts1** [lanternbox/exploreCRS#28]
hI,

We have had a problem with Candidate 4809 Trish Marcus.  When we try to upload the complete profile pack as a PDF on the backend it fails to upload.  It will allow us to open documents and select it but then it fails to go further than the stage in the screen shot (where it appears to be uploading but nothing completes).

Thanks for your help, screen shot is below.

![image](https://cloud.githubusercontent.com/assets/24216430/23115843/62e4f380-f782-11e6-93f3-f23cd8bfaf6f.png)

Robin

**Comment by lantern-jingjing** [comment]
Hi Robin,

Would you please send us the complete profile pack too? So we could investigate it.

Many thanks,
Jingjing

**Comment by RobinWatts1** [comment]
Hi Jing Jing,

 

My apologies, I think in responding to your message I have discovered the issue.  The file is over 20megabytes because the candidate has used lots of rich text and formatting on their CV.  I am guessing this is above the maximum file size for an upload.  We will compress or adapt the file and you can close off the ticket.

 

Thanks for getting back to me so promptly,

 

Kind regards,

 

Robin
