### ISSUE TITLE
Candidate uploaded CV but no green check

### ISSUE THREAD

**Issue by lantern-andrew** [lanternbox/exploreCRS#3]
Candidate "John Smith" ID 1395 uploaded CV on 2016-11-20 but no green check

![screen shot 2016-11-24 at 10 08 00 am](https://cloud.githubusercontent.com/assets/23451422/20584489/e2ae2752-b22d-11e6-9a59-9ec2c6968a25.png)

**Comment by lantern-andrew** [comment]
Thanks for your screenshot. We are adding this to the stage 4 relaunch bug list.

**Comment by Josh1711** [comment]
Hi Andrew,

Any news on the green tick thing? The problem is I am trying to get some candidates live on the database but I can't as there is still the error not allowing us to make these profiles live. Do we know when that will be solved?

Thanks.

**Comment by lantern-andrew** [comment]
Hi Josh, as mentioned in the ticket above, it's on the Stage 4 relaunch bug list - that means the fix will be uploaded together with all the rest of the Stage 4 updates.

In the meantime, if you save the profile and refresh the page, I believe the green check will then be working correctly and you will be allowed to check the "live" box. If that's not the case, please let me know.

**Comment by Josh1711** [comment]
Hi Andrew, I know it is in the update but it seems that when downloading the image, then resizing it and re-uploading, then saving and refreshing doesn't do the trick for the green tick. I know that you mentioned it worked so I have tried it with different profiles and it didn't work. I even tried it where i uploaded a different photo, one that I know works with another candidate profile, and it still didn't work.

![image](https://cloud.githubusercontent.com/assets/23716044/21094051/f5dd4b3a-c08f-11e6-9e3f-95dbfb1735cd.png)
![image](https://cloud.githubusercontent.com/assets/23716044/21094062/0a307a08-c090-11e6-8f10-0a9e39feb649.png)

These are the two I've been working on so far. I have others who have the green tick bug but haven't gotten round to them yet. Thanks.

**Comment by lantern-andrew** [comment]
Hi Josh,

Sorry for my delay getting back to you about this one.

In fact these two candidates have a separate issue: they created their accounts through Google Signin so they don't have a password, which is required for the green check. Just now we removed that requirement and you can approve them.

About the original bug related to the image, we'll fix that this weekend, then confirm back here and close the ticket. Sorry for the confusion and thanks for your patience.

Thanks,
Andrew

**Comment by lantern-andrew** [comment]
Hi Josh, we uploaded another fix today. I think that should address it so I'm closing the ticket - but if you do see it again please send us a reply here. Thanks, Andrew
