### ISSUE TITLE
Missing subjects in candidate profile section

### ISSUE THREAD

**Issue by AngelaCRS** [lanternbox/exploreCRS#9]
Hi,

Our first issue! So we've realized that we are missing "Art" as a choice under Primary and "Physics" under Middle School in the "Subjects/Specialism" section of the candidate profile.

Can these two subject choices be added on in the next update? Please let me know if you need additional information or if what I'm asking isn't clear.

**Comment by lantern-jingjing** [comment]
Hi Angela,

Ok, we will add it to our next update directions and let you know as soon as it is done.

Best regards,
Jingjing

**Comment by lantern-andrew** [comment]
Hi Angela, thanks for your patience. Subjects are posted now - you can find them in the candidate registration and also the new candidate search.
